### PR TITLE
fix defaultTransform did not handle arrays

### PR DESCRIPTION
**Pull request by dready**
this was the last problem in dealing with array values in the search as described in #3.

Highlighting is still another problem.

### CODE REVIEW

**Comment by bebraw** [comment]
Cool. Looks like the linter is choking, though.

* Can you rebase as I bumped dependencies a bit?
* Do you want to resolve highlighting in a separate PR?
* Can you add tests to cover the new functionality?

**Comment by dready** [comment]
sure, will start writing tests right away.

i will look into the highlighting, i have a workaround in place working so it is not a big deal.

**Comment by bebraw** [comment]
Thanks. Included in `1.4.0`. The highlight bits can go in a separate PR. 👍

**Comment by dready** [comment]
thanx, it's not as easy as i thought.. i already tried several possible ways and every time it got messy and did not solve the problem.. this is a tough nut

**Pull request merged**
